global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # For Mimir self-monitoring if needed
  - job_name: 'mimir'
    static_configs:
      - targets: ['mimir:9009']
  
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']

remote_write:
  - url: "http://mimir:9009/api/v1/push"
    # Add any authentication if needed
