services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    volumes:
      - ./:/app
    networks:
      - backend-network

networks:
  backend-network:
    name: luaplatformnetwork
