FROM node:18 AS build
WORKDIR /app
COPY backend/package.json backend/package-lock.json ./
RUN npm install --only=production
COPY . .
RUN npm run build

FROM node:18
WORKDIR /app
COPY --from=build /app /app
CMD ["npm", "start"]
