services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod 
    environment:
      NODE_ENV: production
    restart: always
#docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build