services:
  app:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile  # Uses Dockerfile.prod for production
    ports:
      - "5000:5000" 
    env_file:
      - .env
    networks:
      - backend-network
    depends_on:
      - db

  db:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db
    networks:
      - backend-network
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    networks:
      - backend-network

volumes:
  mongo_data:

networks:
  backend-network:
