datasources:
- name: Mimir
  type: prometheus
  default: true
  access: proxy
  url: http://mimir:9009/prometheus
  # jsonData:
  #   tlsSkipVerify: true
  #   tlsAuth: false
  #   tlsAuthWithCACert: false
- name: Loki
  type: loki
  access: proxy
  url: http://loki:3100
- name: Tempo
  type: tempo
  access: proxy
  url: http://tempo:3200