# TODO: fasa5 lkol w a3mal docker file 
FROM python:3.8
RUN apt-get update
RUN apt-get install -y make
RUN pip install --upgrade pip
COPY requirements.txt /app/requirements.txt
RUN pip install -r /app/requirements.txt
COPY . /app
WORKDIR /app
RUN make
CMD python app.py
